# Generated by Django 3.0.1 on 2019-12-28 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('millage', models.IntegerField()),
                ('condition', models.TextField(blank=True)),
                ('registration_year', models.IntegerField()),
                ('registration_number', models.IntegerField()),
                ('last_mot_date', models.DateField()),
                ('mot_due', models.DateField()),
                ('insurance_due', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('repair_needed', models.TextField(blank=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastEditDate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mot_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_notes', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mot_app.User')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mot_app.Vehicle')),
            ],
        ),
    ]
