# Generated by Django 3.0.1 on 2019-12-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mot_app', '0003_auto_20191228_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='creationDate',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='remind_notes',
            new_name='reminder_note',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='registration_number',
            new_name='current_vehicle_reg_no',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='creationDate',
            new_name='join_date',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='creationDate',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='lastEditDate',
            new_name='last_edit_date',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='repair_needed',
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(default='2019-02-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='extra_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='repair_needed_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_mot_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
