# Generated by Django 3.0.1 on 2019-12-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mot_app', '0004_auto_20191229_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
