# Generated by Django 3.0.1 on 2019-12-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mot_app', '0007_auto_20191230_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
