# Generated by Django 3.0.1 on 2019-12-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mot_app', '0008_auto_20191230_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='full_name',
        ),
    ]
