# Generated by Django 3.0.1 on 2019-12-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mot_app', '0009_auto_20191230_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_vehicle_reg_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
