# Generated by Django 3.0.1 on 2019-12-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mot_app', '0010_auto_20191231_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
