# Generated by Django 3.0.1 on 2019-12-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mot_app', '0011_auto_20191231_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.CharField(default='ford', max_length=255),
            preserve_default=False,
        ),
    ]
