# Generated by Django 3.0.1 on 2019-12-31 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mot_app', '0012_auto_20191231_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mot_app.Vehicle'),
        ),
    ]
